{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
{{ $suffix := "metrics" -}}
metadata:  {{- include "common.resourceMetadata" (dict "suffix" $suffix "annotations" .Values.metrics.service.annotations "dot" . ) | nindent 2 }}
spec:
  type: {{ .Values.metrics.service.type }}
  {{- if and (eq .Values.metrics.service.type "LoadBalancer") .Values.metrics.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.metrics.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: metrics
  selector: {{- include "common.selectors" . | nindent 4 }}
{{- end }}
