{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fluentd.serviceAccountName" . }}
  labels: {{- include "common.labels" . | nindent 4 }}
{{- end -}}