{{- if and .Values.aggregator.enabled .Values.aggregator.service.ports -}}
apiVersion: v1
kind: Service
{{ $suffix := "headless" -}}
{{ $labels := (dict "app.kubernetes.io/component" "aggregator") -}}
metadata:  {{- include "common.resourceMetadata" (dict "suffix" $suffix "labels" $labels "dot" . ) | nindent 2 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  {{- range $key, $value := .Values.aggregator.service.ports }}
    - name: {{ $key }}
      {{ toYaml $value | nindent 6 }}
  {{- end }}
  selector: {{- include "common.matchLabels" (dict "matchLabels" $labels "dot" . ) | nindent 4 }}
{{- end -}}
