# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

dependencies:
  - name: common
    version: ~7.x-0
    repository: '@local'
  - name: multicloud-emco-common
    version: ~0.x-0
    repository: 'file://../multicloud-emco-common'
