# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

debugEnabled: false

# application configuration is via config files

# default number of instances
replicaCount: 1

nodeSelector: {}

affinity: {}

